// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $about from "./routes/about.tsx";
import * as $api_bildungsplan from "./routes/api/bildungsplan.ts";
import * as $api_chat from "./routes/api/chat.ts";
import * as $api_debug from "./routes/api/debug.ts";
import * as $api_grading from "./routes/api/grading.ts";
import * as $api_imagegen from "./routes/api/imagegen.ts";
import * as $api_learning_paths from "./routes/api/learning-paths.ts";
import * as $api_mail from "./routes/api/mail.ts";
import * as $api_mailsync from "./routes/api/mailsync.ts";
import * as $api_music from "./routes/api/music.ts";
import * as $api_openrouter_models from "./routes/api/openrouter-models.ts";
import * as $api_papers from "./routes/api/papers.ts";
import * as $api_stt from "./routes/api/stt.ts";
import * as $api_tts from "./routes/api/tts.ts";
import * as $api_wikipedia from "./routes/api/wikipedia.ts";
import * as $index from "./routes/index.tsx";
import * as $ChatAgreement from "./islands/ChatAgreement.tsx";
import * as $ChatAgreementOrIsland from "./islands/ChatAgreementOrIsland.tsx";
import * as $ChatIsland from "./islands/ChatIsland.tsx";
import * as $Header from "./islands/Header.tsx";
import * as $Menu from "./islands/Menu.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/about.tsx": $about,
    "./routes/api/bildungsplan.ts": $api_bildungsplan,
    "./routes/api/chat.ts": $api_chat,
    "./routes/api/debug.ts": $api_debug,
    "./routes/api/grading.ts": $api_grading,
    "./routes/api/imagegen.ts": $api_imagegen,
    "./routes/api/learning-paths.ts": $api_learning_paths,
    "./routes/api/mail.ts": $api_mail,
    "./routes/api/mailsync.ts": $api_mailsync,
    "./routes/api/music.ts": $api_music,
    "./routes/api/openrouter-models.ts": $api_openrouter_models,
    "./routes/api/papers.ts": $api_papers,
    "./routes/api/stt.ts": $api_stt,
    "./routes/api/tts.ts": $api_tts,
    "./routes/api/wikipedia.ts": $api_wikipedia,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/ChatAgreement.tsx": $ChatAgreement,
    "./islands/ChatAgreementOrIsland.tsx": $ChatAgreementOrIsland,
    "./islands/ChatIsland.tsx": $ChatIsland,
    "./islands/Header.tsx": $Header,
    "./islands/Menu.tsx": $Menu,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
