/// <reference path="../types.d.ts" />
// internalization/learning-content.ts
//
// Interface strings for the learning paths modal. Kept in its own file so the
// large content module and the chat translations never collide.

export const learningContent: InternalizationContent = {
  en: {
    chooseModuleHint: "Choose a module.",
    backToModules: "Back to the modules",
    tasksTitle: "Check yourself",
    tasksIntro:
      "Three exercises: one to recall, one to think through, one with no right answer at all. Nothing you type here is saved - these are for thinking with.",
    tasksNoAnswers:
      "There is no answer key on purpose. Everything you need for the first two is in this path, and the third one is yours alone.",
    levelRecall: "Recall",
    levelCompare: "Think it through",
    levelThink: "Your turn",
    hintLabel: "Nudge:",
    answerHere: "Write your answer here...",
    printSheet: "Worksheet",
    printHint:
      'Opens a printable version of this path with the exercises. Choose "Save as PDF" in the print dialogue to keep it as a file.',
    worksheet: "Worksheet",
    sheetName: "Name:",
    sheetDate: "Date:",
    sheetSources: "Sources",
    sheetFooter: "Computing basics - free to copy for teaching",
    popupBlocked:
      "The browser blocked the new window. Allow pop-ups for this page, then try again.",
    title: "Learning paths",
    subtitle: "Understand computers - one screen at a time",
    close: "Close",
    chooseSubject: "Which subject would you like to explore?",
    chooseSubjectHint:
      "More subjects will follow. Pick a tile to see its learning paths.",
    choosePath: "Pick a learning path",
    choosePathHint:
      "Every path is a short read, split into a few screens. You can stop any time - we remember where you were.",
    screens: "screens",
    screen: "screen",
    minutes: "min",
    readingTime: "reading time",
    start: "Start",
    continueReading: "Continue",
    startOver: "Start over",
    resumeBanner: "You stopped here last time",
    resumeOpen: "Continue reading",
    resumeDismiss: "Not now",
    back: "Back",
    backToSubjects: "All subjects",
    backToPaths: "All paths",
    next: "Next",
    previous: "Previous",
    pageOf: "Page {current} of {total}",
    finish: "Finished",
    finishedTitle: "Nicely done!",
    finishedBody:
      "You made it through the whole path. Pick another one, or read this one again - the second time is where things click.",
    finishedAnother: "Pick another path",
    finishedAgain: "Read again",
    sourcesTitle: "Where these facts come from",
    sourcesHint: "Every link opens in a new tab.",
    doneBadge: "read",
    inProgressBadge: "in progress",
    overviewTitle: "In this path",
    tryIt: "Try it yourself",
    remember: "Worth remembering",
    funFact: "Fun fact",
    heads: "Careful",
    numbers: "The numbers",
  },
  de: {
    chooseModuleHint: "Wähle ein Modul.",
    backToModules: "Zurück zu den Modulen",
    tasksTitle: "Überprüfe dich selbst",
    tasksIntro:
      "Drei Aufgaben: eine zum Erinnern, eine zum Durchdenken und eine, auf die es keine richtige Antwort gibt. Was du hier eintippst, wird nirgends gespeichert - es ist zum Denken da.",
    tasksNoAnswers:
      "Lösungen gibt es absichtlich keine. Alles für die ersten beiden Aufgaben steht in diesem Lernpfad, und die dritte gehört ganz dir.",
    levelRecall: "Erinnern",
    levelCompare: "Durchdenken",
    levelThink: "Deine Meinung",
    hintLabel: "Denkanstoß:",
    answerHere: "Schreib deine Antwort hier hin...",
    printSheet: "Arbeitsblatt",
    printHint:
      'Öffnet eine druckbare Fassung dieses Lernpfads samt Aufgaben. Im Druckfenster "Als PDF speichern" wählen, dann hast du es als Datei.',
    worksheet: "Arbeitsblatt",
    sheetName: "Name:",
    sheetDate: "Datum:",
    sheetSources: "Quellen",
    sheetFooter:
      "Informatische Grundbildung - für den Unterricht frei kopierbar",
    popupBlocked:
      "Der Browser hat das neue Fenster blockiert. Erlaube Pop-ups für diese Seite und versuch es noch einmal.",
    title: "Lernpfade",
    subtitle: "Computer verstehen - ein Bildschirm nach dem anderen",
    close: "Schließen",
    chooseSubject: "Welches Fach möchtest du erkunden?",
    chooseSubjectHint:
      "Weitere Fächer folgen. Klick auf eine Kachel, um ihre Lernpfade zu sehen.",
    choosePath: "Wähle einen Lernpfad",
    choosePathHint:
      "Jeder Pfad ist ein kurzer Text, aufgeteilt in ein paar Bildschirme. Du kannst jederzeit aufhören - wir merken uns, wo du warst.",
    screens: "Bildschirme",
    screen: "Bildschirm",
    minutes: "Min.",
    readingTime: "Lesezeit",
    start: "Starten",
    continueReading: "Weiterlesen",
    startOver: "Von vorn",
    resumeBanner: "Hier hast du zuletzt aufgehört",
    resumeOpen: "Weiterlesen",
    resumeDismiss: "Jetzt nicht",
    back: "Zurück",
    backToSubjects: "Alle Fächer",
    backToPaths: "Alle Lernpfade",
    next: "Weiter",
    previous: "Zurück",
    pageOf: "Seite {current} von {total}",
    finish: "Fertig",
    finishedTitle: "Stark gemacht!",
    finishedBody:
      "Du hast den ganzen Pfad geschafft. Nimm dir den nächsten vor - oder lies diesen noch einmal. Beim zweiten Mal macht es meistens erst richtig klick.",
    finishedAnother: "Nächsten Pfad wählen",
    finishedAgain: "Nochmal lesen",
    sourcesTitle: "Woher diese Angaben stammen",
    sourcesHint: "Jeder Link öffnet sich in einem neuen Tab.",
    doneBadge: "gelesen",
    inProgressBadge: "angefangen",
    overviewTitle: "In diesem Pfad",
    tryIt: "Zum Ausprobieren",
    remember: "Zum Merken",
    funFact: "Kurios",
    heads: "Achtung",
    numbers: "Die Zahlen",
  },
};
