/// <reference path="../types.d.ts" />
// internalization/learning-content.ts
//
// Interface strings for the learning paths modal. Kept in its own file so the
// large content module and the chat translations never collide.

export const learningContent: InternalizationContent = {
  en: {
    title: "Learning paths",
    subtitle: "Understand computers - one screen at a time",
    close: "Close",
    chooseSubject: "Which subject would you like to explore?",
    chooseSubjectHint:
      "More subjects will follow. Pick a tile to see its learning paths.",
    choosePath: "Pick a learning path",
    choosePathHint:
      "Every path is a short read, split into a few screens. You can stop any time - we remember where you were.",
    screens: "screens",
    screen: "screen",
    minutes: "min",
    readingTime: "reading time",
    start: "Start",
    continueReading: "Continue",
    startOver: "Start over",
    resumeBanner: "You stopped here last time",
    resumeOpen: "Continue reading",
    resumeDismiss: "Not now",
    back: "Back",
    backToSubjects: "All subjects",
    backToPaths: "All paths",
    next: "Next",
    previous: "Previous",
    pageOf: "Page {current} of {total}",
    finish: "Finished",
    finishedTitle: "Nicely done!",
    finishedBody:
      "You made it through the whole path. Pick another one, or read this one again - the second time is where things click.",
    finishedAnother: "Pick another path",
    finishedAgain: "Read again",
    sourcesTitle: "Where these facts come from",
    sourcesHint: "Every link opens in a new tab.",
    doneBadge: "read",
    inProgressBadge: "in progress",
    overviewTitle: "In this path",
    tryIt: "Try it yourself",
    remember: "Worth remembering",
    funFact: "Fun fact",
    heads: "Careful",
    numbers: "The numbers",
  },
  de: {
    title: "Lernpfade",
    subtitle: "Computer verstehen - ein Bildschirm nach dem anderen",
    close: "Schließen",
    chooseSubject: "Welches Fach möchtest du erkunden?",
    chooseSubjectHint:
      "Weitere Fächer folgen. Klick auf eine Kachel, um ihre Lernpfade zu sehen.",
    choosePath: "Wähle einen Lernpfad",
    choosePathHint:
      "Jeder Pfad ist ein kurzer Text, aufgeteilt in ein paar Bildschirme. Du kannst jederzeit aufhören - wir merken uns, wo du warst.",
    screens: "Bildschirme",
    screen: "Bildschirm",
    minutes: "Min.",
    readingTime: "Lesezeit",
    start: "Starten",
    continueReading: "Weiterlesen",
    startOver: "Von vorn",
    resumeBanner: "Hier hast du zuletzt aufgehört",
    resumeOpen: "Weiterlesen",
    resumeDismiss: "Jetzt nicht",
    back: "Zurück",
    backToSubjects: "Alle Fächer",
    backToPaths: "Alle Lernpfade",
    next: "Weiter",
    previous: "Zurück",
    pageOf: "Seite {current} von {total}",
    finish: "Fertig",
    finishedTitle: "Stark gemacht!",
    finishedBody:
      "Du hast den ganzen Pfad geschafft. Nimm dir den nächsten vor - oder lies diesen noch einmal. Beim zweiten Mal macht es meistens erst richtig klick.",
    finishedAnother: "Nächsten Pfad wählen",
    finishedAgain: "Nochmal lesen",
    sourcesTitle: "Woher diese Angaben stammen",
    sourcesHint: "Jeder Link öffnet sich in einem neuen Tab.",
    doneBadge: "gelesen",
    inProgressBadge: "angefangen",
    overviewTitle: "In diesem Pfad",
    tryIt: "Zum Ausprobieren",
    remember: "Zum Merken",
    funFact: "Kurios",
    heads: "Achtung",
    numbers: "Die Zahlen",
  },
};
